# CONFIGURAÇÃO PARA POSTGRES  
development:
  adapter: postgresql
  database: ensino_development
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: ensino_test
  username: postgres
  password: postgres